language: php

php:
  - 5.3
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction

script: ./vendor/bin/phpunit

after_script:
  - php ./vendor/bin/coveralls
